# Generated by Django 3.0.4 on 2020-04-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0002_auto_20200402_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isuario', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='tattoo',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tattoo.Comentario'),
        ),
    ]
