# Generated by Django 3.0.4 on 2020-04-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0003_auto_20200402_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='tattoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tattoo.Tattoo'),
        ),
    ]
